### ISSUE TITLE
Introduce refract serialisation versioning

### ISSUE THREAD

**Issue by kylef** [apiaryio/api.apiblueprint.org#19]
I think we should introduce versioning of Refract serialisations. We should add the Refract JSON Serialisation version to the exposed interface. I want to be clear, this is not Refract versioning itself, but the version of the serialisation format as the serialisation is decoupled from Refract.

There are planned serialisation formats changes in the future, especially upcoming to 1 of the serialisation. It should be rare that serialisation will change afterwards, however we should have clear versioning to make it clear to consumers if there ever was changes. This would be similar to how HTTP  handles versioning. The versioning is informative rather than contractual. The current version would be returned in documents for example: `application/vnd.refract+json; version=0.6` which makes it clear on the serialisation version used.

To aid migration to new versions we may accept serialising to multiple versions of a Refract serialisation for a short period of time while migrating allowing clients to move to the new version.

If a client requests `Accept: application/vnd.refract+json` they should receive the latest supported version.

If the client requests a specific supported version (`Accept: application/vnd.refract+json; version=0.6`) then that version may be returned if supported.

When a client requests an unsupported version (`Accept: application/vnd.refract+json; version=4`) and error should be returned.

**Comment by smizell** [comment]
I wonder if this would be a good opportunity to consider an API Elements media type for API Blueprint and Swagger parse results rather than Refract-specific. Currently, it looks like `application/vnd.refract.parse-result+json` is used, however, this document has been [deprecated](https://github.com/refractproject/refract-spec/blob/master/namespaces/parse-result-namespace.md) in favor of moving it to API Elements.

Additionally, API Elements has its [own Refract definitions](http://api-elements.readthedocs.io/en/latest/element-definitions/#base-api-element-object). It makes me think that something like `application/vnd.api-elements+json` would be more appropriate and make more sense to people using the parser. You could then specify the Refract serialization version that is used alongside the media type.

I think it would also be helpful to consider including the version in the actual document itself, so that, if persisted somewhere, the origin and version can both be determined. You may want to also add some form of deprecation notice alongside the version, so that client developers see that there is not only a version in the document, but a potential deprecation link if a specific version is deprecated.

If you decide to add version and a deprecation notice, I think meta links should be used. HAL has a `deprecated` property, but it is not a defined link relation, so you may want to consider a custom one. For version, there are some link relations defined in [RFC 5829](https://tools.ietf.org/html/rfc5829), though this could be custom as well.

---

With all of that said, I agree with the idea of this PR. I like how the version coincides with the serialization and not the spec itself. I also personally agree with everything else around versions, what happens when a version is not in the `Accept` header, and what happens with unsupported versions. Good stuff.

**Comment by w-vi** [comment]
Regarding the version in the document itself it is definitely going to happen as otherwise the whole versioning becomes useless. I was thinking to add it in some meta with a link to version spec etc. I don't think that deprecation link makes sense to be stored in the document itself but definitely it should be part of the response from the parsing service if an old version is requested.

**Comment by smizell** [comment]
Yeah, on the versioning, that's what I'd do—use a meta link to link to that specific version. The deprecation link would then be another meta link that shows up on the document in the response only if the returned version is being deprecated. The deprecated link would be to documentation about that specific parser implementation, why it's no longer supporting a specific version, and when it's planned to be fully removed.

In this situation, the version link would be a link to the spec, while the deprecation link is a link for a specific implementation. Additionally, a deprecation link could be used to deprecate anything in the document, not just versions, so it could act as a hint for people to note when something is changing in the specific parser, which may or may not be related to the spec. I think you need something like if a version-less `Accept` header is going to be used, because you need a way to evolve the document structure alongside client developers.

I personally think a link would be the best option here. If you're wanting to keep it out of the document, a link header could be used. However, I'm not sure what gain it provides in putting it in the header.

**Comment by w-vi** [comment]
Deprecation of the supported version in parsing service is not related to the version of serialization of the document. I feel that it mixes unrelated things. The serialization has some version, that makes sense. But I can have same ADD parsed in different time and have a different result because the latter one includes deprecation notice, feels strange I'd expect the documents to be the same.

**Comment by smizell** [comment]
@w-vi that's a good point.

I think the difference is that I'm looking at this from a web API perspective. The response from the API with a specified media type is the representation of the internal application logic and not only the parser results, which changes and evolves. For instance, with a locally-installed parser, you can include console deprecation notices outside the context of the parse results. Over the web, the serialization feels to me like you are representing the entire state with the ability to evolve it over time.

If the goal is to keep the parse results pure and reproducible, I do what you are saying is correct.

**Comment by w-vi** [comment]
True, it depends on how you think about it. Is refract tied to API (in broad sense including command line) or is it some representation of data. I still feel that it should be separated as I can see usage of refract out of the web API world.

**Comment by w-vi** [comment]
Or maybe there is a middle way, the result of the service should clearly state what is the parse result of the ADD and what is the service related information.

**Comment by smizell** [comment]
> Is refract tied to API (in broad sense including command line) or is it some representation of data.

Refract itself is merely a structure for representing data, so it doesn't really care where it comes from as far as the spec goes. API Elements defines information for an API along with parse results for the API description document, so it's dependent on that implementation—it may or may not include parse result information. Drafter, for instance, has parsing information, such as special origin links and inferred links that are specific only to Drafter. The spec merely says that it may have those links in any element.

> Or maybe there is a middle way, the result of the service should clearly state what is the parse result of the ADD and what is the service related information.

I agree. Conceptually, the parser is providing the parse results at that given point in time and in that context. Those results are specific to a given implementation, so when speaking of a `version`, it is for example Drafter's implementation of that version of the serialization format.

The difference here is that the API will be a single version of Drafter in time, whereas locally, someone may have multiple versions of Drafter or a differing version (unless the API will support multiple versions of Drafter). Therefore, when it's said the response is for "version 1" of the serialization format from the API, for example, it is actually the current implementation of "version 1" in the current version deployed of Drafter. That implementation may change, so even implementation of "version 1" may change (e.g. bug fixes).

I've said all of this to say there is a different view of things from the APIs perspective, and you may want service information like you've said of not only the current version of the serialization format, but maybe even Drafter version used for those parse results. This could be done by wrapping the parse results in a plain JSON object, or even creating a new element for server information for the API results. I think you're definitely on the right track with the distinction of parse results and service information.

Sorry for being long winded. Hope I didn't muddy the water here.

**Comment by smizell** [comment]
I want to add a short example to show the distinction:

Locally, the results of serialization format v1 and Drafter v1 should always be the same. However, the results of serialization format v1 and Drafter v2 may be different. The API will only have one version, so over time, the response for serialization format v1 may change.

Ok, I think I've typed enough :)

**Comment by pksunkara** [comment]
> Locally, the results of serialization format v1 and Drafter v1 should always be the same. However, the results of serialization format v1 and Drafter v2 may be different. The API will only have one version, so over time, the response for serialization format v1 may change.

That's the main issue I have with serialisation versions. Why do we need it? We can version API Elements output from Drafter directly if we need to.

**Comment by kylef** [comment]
This has been implemented.
